trigger:
  - master

pool:
  vmImage: "ubuntu-20.04"

steps:
  - script: |
      python -m pip install --upgrade pip setuptools wheel pipenv
      python -m pipenv install -d --system

    displayName: "Installing dependencies"

  - script: |
      pipenv run lint

    displayName: "Check code style with flake8"
